#!/usr/bin/env bash
# scripts/systemd/install.sh — установить samurai-* unit-файлы в /etc/systemd/system/
#
# Требует sudo. Подставляет реальный путь к репо и юзера в шаблоны.
#
# Использование:
#   sudo ./scripts/systemd/install.sh                # все unit'ы
#   sudo ./scripts/systemd/install.sh robot          # только samurai-robot
#   sudo ./scripts/systemd/install.sh robot bridge   # robot и bridge
#   sudo ./scripts/systemd/install.sh --uninstall    # удалить все

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SAMURAI_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=../lib/common.sh
source "$SAMURAI_ROOT/scripts/lib/common.sh"

UNIT_DIR="/etc/systemd/system"
ALL_UNITS=(robot compute bridge agent)

require_root() {
    if [[ $EUID -ne 0 ]]; then
        die "Требуется sudo: ${YELLOW}sudo $0 $*${NC}"
    fi
}

determine_user() {
    # SUDO_USER если запущено через sudo, иначе текущий
    if [[ -n "${SUDO_USER:-}" && "$SUDO_USER" != "root" ]]; then
        echo "$SUDO_USER"
    else
        # На Pi обычно есть пользователь pi
        if id -u pi &>/dev/null; then
            echo "pi"
        else
            die "Не могу определить целевого пользователя. Запусти: sudo -u <user> $0 ..."
        fi
    fi
}

uninstall_units() {
    require_root "--uninstall"
    log_step "Удаление samurai-* units"
    local unit
    for unit in "${ALL_UNITS[@]}"; do
        local svc="samurai-${unit}.service"
        if [[ -f "$UNIT_DIR/$svc" ]]; then
            systemctl stop "$svc" 2>/dev/null || true
            systemctl disable "$svc" 2>/dev/null || true
            rm -f "$UNIT_DIR/$svc"
            log_ok "Удалён $svc"
        else
            log_info "$svc не установлен (пропуск)"
        fi
    done
    systemctl daemon-reload
    log_ok "Готово. systemctl daemon-reload выполнен."
}

install_unit() {
    local unit="$1" user="$2"
    local template="$SCRIPT_DIR/samurai-${unit}.service"
    local target="$UNIT_DIR/samurai-${unit}.service"

    [[ -f "$template" ]] || die "Шаблон не найден: $template"

    log_info "Установка samurai-${unit}.service (user=$user, root=$SAMURAI_ROOT)"
    sed \
        -e "s|__SAMURAI_USER__|${user}|g" \
        -e "s|__SAMURAI_ROOT__|${SAMURAI_ROOT}|g" \
        "$template" > "$target"

    chmod 644 "$target"
    log_ok "  → $target"
}

# ── Генерация /etc/sudoers.d/samurai-robot для NOPASSWD-рестарта с ноута ───
# Использование: install_sudoers_remote_deploy <user> [sudoers_dir]
# sudoers_dir override-ится только для тестов (default /etc/sudoers.d).
install_sudoers_remote_deploy() {
    local user="$1"
    local sudoers_dir="${2:-/etc/sudoers.d}"
    local target="$sudoers_dir/samurai-robot"
    local tmpfile
    tmpfile=$(mktemp)

    cat > "$tmpfile" <<EOF
# Generated by ./scripts/systemd/install.sh --with-remote-deploy
# Allows $user to restart/inspect samurai-robot.service without password,
# so ./samurai.sh compute --pi can ssh-restart the service over LAN.
$user ALL=(root) NOPASSWD: /bin/systemctl restart samurai-robot, \\
                          /bin/systemctl is-active samurai-robot, \\
                          /bin/systemctl status samurai-robot, \\
                          /bin/journalctl -u samurai-robot *
EOF

    # visudo -cf обязателен — битый файл может залочить sudo.
    if command -v visudo &>/dev/null; then
        if ! visudo -cf "$tmpfile" &>/dev/null; then
            rm -f "$tmpfile"
            die "Сгенерированный sudoers не прошёл visudo -cf"
        fi
    fi

    # Атомарная установка с правильными правами.
    # Для тестов (non-root, override sudoers_dir) — fallback на install -m без -o.
    install -m 0440 -o root -g root "$tmpfile" "$target" 2>/dev/null \
        || install -m 0440 "$tmpfile" "$target"
    rm -f "$tmpfile"

    log_ok "Установлен $target (NOPASSWD для $user)"
}

main() {
    local with_remote_deploy=false
    local user_arg=""
    local positional=()

    # Парсинг аргументов.
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --uninstall|-u)
                uninstall_units; exit 0 ;;
            -h|--help)
                cat <<EOF
Использование:
  sudo $0 [OPTIONS] [unit1 unit2 ...]   # установить (default: все)
  sudo $0 --uninstall                    # удалить все

Опции:
  --user USER             Целевой юзер (default: \$SUDO_USER или 'pi')
  --with-remote-deploy    Также установить /etc/sudoers.d/samurai-robot
                          с NOPASSWD для удалённого рестарта с ноута
                          (./samurai.sh compute --pi)

После установки:
  sudo systemctl enable --now samurai-robot     # автозапуск
  systemctl status samurai-robot                # статус
  journalctl -u samurai-robot -f                # live-логи
EOF
                exit 0 ;;
            --user)
                user_arg="$2"; shift 2 ;;
            --with-remote-deploy)
                with_remote_deploy=true; shift ;;
            -*)
                die "Неизвестный флаг: $1 (см. --help)" ;;
            *)
                positional+=("$1"); shift ;;
        esac
    done

    require_root

    local user
    if [[ -n "$user_arg" ]]; then
        user="$user_arg"
    else
        user=$(determine_user)
    fi

    print_banner "S A M U R A I   S Y S T E M D" "Установка unit-файлов"
    log_ok "Целевой пользователь: ${BOLD}$user${NC}"
    log_ok "Корень репо:          ${BOLD}$SAMURAI_ROOT${NC}"
    log_ok "Unit-директория:      ${BOLD}$UNIT_DIR${NC}"
    echo ""

    # Создать директорию состояния (для логов и lock-файлов)
    mkdir -p /var/lib/samurai/{logs,locks}
    chown -R "$user:$user" /var/lib/samurai
    log_ok "Создана /var/lib/samurai (owner=$user)"

    # Установить logrotate-правило (если logrotate доступен)
    local logrotate_src="$SCRIPT_DIR/samurai.logrotate"
    if [[ -f "$logrotate_src" ]] && command -v logrotate >/dev/null 2>&1; then
        # sed подставит реальный user (по умолчанию шаблон ссылается на pi)
        sed "s/create 0644 pi pi/create 0644 $user $user/" \
            "$logrotate_src" > /etc/logrotate.d/samurai
        chmod 644 /etc/logrotate.d/samurai
        log_ok "Установлен /etc/logrotate.d/samurai (rotate 7d, maxsize 50M)"
    elif [[ -f "$logrotate_src" ]]; then
        log_info "logrotate не установлен — пропуск config (manual-run logs не ротируются)"
    fi

    # Какие unit'ы устанавливать
    local targets=()
    if [[ ${#positional[@]} -eq 0 ]]; then
        targets=("${ALL_UNITS[@]}")
    else
        targets=("${positional[@]}")
    fi

    log_step "Установка"
    local t
    for t in "${targets[@]}"; do
        local found=false
        local v
        for v in "${ALL_UNITS[@]}"; do
            [[ "$t" == "$v" ]] && { found=true; break; }
        done
        $found || die "Неизвестный unit: $t (доступны: ${ALL_UNITS[*]})"
        install_unit "$t" "$user"
    done

    log_step "systemctl daemon-reload"
    systemctl daemon-reload
    log_ok "daemon-reload OK"

    echo ""
    log_step "Что дальше"
    echo ""
    echo -e "  ${BOLD}Включить автозапуск:${NC}"
    for t in "${targets[@]}"; do
        echo -e "    ${YELLOW}sudo systemctl enable --now samurai-${t}${NC}"
    done
    echo ""
    echo -e "  ${BOLD}Проверить статус:${NC}"
    for t in "${targets[@]}"; do
        echo -e "    ${YELLOW}systemctl status samurai-${t}${NC}"
    done
    echo ""
    echo -e "  ${BOLD}Live-логи:${NC}"
    for t in "${targets[@]}"; do
        echo -e "    ${YELLOW}journalctl -u samurai-${t} -f${NC}"
    done
    echo ""
    echo -e "  ${BOLD}Удалить:${NC}"
    echo -e "    ${YELLOW}sudo $0 --uninstall${NC}"
    echo ""
    log_warn "ВАЖНО: установи Python-зависимости ВРУЧНУЮ перед enable"
    log_warn "       (systemd не делает pip install автоматически)"
    log_warn "       Pi:    pip3 install paho-mqtt PyYAML smbus2 gpiozero"
    log_warn "       Ноут:  pip3 install pyserial fastapi uvicorn pydantic"

    if [[ "$with_remote_deploy" == "true" ]]; then
        log_step "Установка /etc/sudoers.d/samurai-robot"
        install_sudoers_remote_deploy "$user"
    fi
}

# Запускать main только при прямом исполнении, не при source (для тестов).
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
