function export_to_yaml(Ad, Bd, K_lqr, K_mpc, L, Pf, p, yaml_path, mps)
% EXPORT_TO_YAML — запись рассчитанных матриц в config.yaml (раздел `control:`).
%
%   ЭТО МОСТ MATLAB → ROBOT.
%   После запуска main.m все матрицы регуляторов готовы. Эта функция
%   ПЕРЕЗАПИСЫВАЕТ блок `control:` в config.yaml в корне проекта,
%   сохраняя ВСЕ остальные секции файла нетронутыми. Робот при следующем
%   старте подхватит свежие коэффициенты — перезапуск Python НЕ нужен.
%
%   АЛГОРИТМ:
%     1. Читаем config.yaml как текст (UTF-8).
%     2. Ищем строку, начинающуюся с `control:` без отступа.
%     3. Находим конец блока — следующая строка с зануленным отступом
%        (или маркер `# === end of auto-generated control: block ===`).
%     4. Заменяем диапазон строк новым YAML-блоком.
%     5. Записываем обратно.
%
%   Если `control:` не найден — приписываем блок в конец файла.
%
%   ЗАЩИТА ОТ ПЕРЕЗАПИСИ:
%   В config.yaml есть поле `control.matrices.override`. Если пользователь
%   правил матрицы вручную и не хочет их потерять — должен поставить
%   `override: true`. Эта функция матрицы всё равно перезапишет
%   (лучше всего удалить override после ручной правки), но в комментариях
%   подскажет, как остановить автоматику.
%
%   ВХОДЫ:
%     Ad, Bd       — дискретные матрицы объекта
%     K_lqr        — LQR-регулятор (2 × n)
%     K_mpc        — MPC явный коэффициент первого шага (2 × n)
%     L            — наблюдатель Луенбергера (n × m); [] чтобы пропустить
%     Pf           — терминальный штраф MPC (= P_∞ из DARE)
%     p            — параметры от samurai_params()
%     yaml_path    — полный путь к config.yaml (если [] — берётся ../config.yaml)
%     mps          — (опц.) struct канонической модели МПС. Если задан,
%                    функция дополнительно пишет/заменяет блок `mps:`.
%                    Поля: A_c, B_c, C, D (НЕПРЕРЫВНЫЕ), tau_v, tau_w, Ts,
%                    Q, R, N, u_min, u_max.
%
%   АСИММЕТРИЯ КОНТРАКТА:
%     control.matrices.A/B — ДИСКРЕТНЫЕ Ad/Bd (legacy-модель).
%     mps.matrices.A/B     — НЕПРЕРЫВНЫЕ A_c/B_c (бэкенд ZOH-дискретизирует).

  if nargin < 8 || isempty(yaml_path)
    yaml_path = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
                         'config.yaml');
  end

  % ── Сборка нового YAML-блока как cell-массива строк ───────────
  % Пишем человеко-читаемый комментарий, потом параметры, потом матрицы.
  L_block = {};
  L_block{end+1} = '# === control: section auto-generated by matlab/main.m ===';
  L_block{end+1} = '# Edit weights/limits/poles below; rerun matlab/main.m to update matrices.';
  L_block{end+1} = '# Подробное описание: latex_doc/control_theory/main.pdf';
  L_block{end+1} = 'control:';
  L_block{end+1} = '  mode: "off"           # off | lqr | mpc | modal';
  L_block{end+1} = '';
  L_block{end+1} = '  plant:';
  L_block{end+1} = sprintf('    v0:    %.4f', p.v0);
  L_block{end+1} = sprintf('    tau_v: %.4f', p.tau_v);
  L_block{end+1} = sprintf('    tau_w: %.4f', p.tau_w);
  L_block{end+1} = sprintf('    Ts:    %.4f', p.Ts);
  L_block{end+1} = '';
  L_block{end+1} = '  weights:';
  L_block{end+1} = sprintf('    Q_diag: %s', mat2yaml(diag(p.Q)'));
  L_block{end+1} = sprintf('    R_diag: %s', mat2yaml(diag(p.R)'));
  L_block{end+1} = '';
  L_block{end+1} = '  limits:';
  L_block{end+1} = sprintf('    u_min: %s', mat2yaml(p.u_min'));
  L_block{end+1} = sprintf('    u_max: %s', mat2yaml(p.u_max'));
  L_block{end+1} = '';
  L_block{end+1} = '  mpc:';
  L_block{end+1} = sprintf('    horizon_N: %d', p.N);
  L_block{end+1} = '    solver:    "clip"   # clip | qp';
  L_block{end+1} = '';
  L_block{end+1} = '  modal:';
  L_block{end+1} = sprintf('    poles_continuous: %s', mat2yaml(p.poles_continuous'));
  L_block{end+1} = sprintf('    observer_speedup: %.1f', p.observer_speedup);
  L_block{end+1} = '';
  L_block{end+1} = '  matrices:';
  L_block{end+1} = '    override: false      # set true to disable matlab/main.m updates';
  L_block{end+1} = sprintf('    A:  %s', mat2yaml_2d(Ad));
  L_block{end+1} = sprintf('    B:  %s', mat2yaml_2d(Bd));
  L_block{end+1} = sprintf('    K:     %s     # LQR gain (2 x n) — used in mode: lqr', mat2yaml_2d(K_lqr));
  L_block{end+1} = sprintf('    K_mpc: %s     # MPC explicit first-step gain — used in mode: mpc', mat2yaml_2d(K_mpc));
  if ~isempty(L)
    L_block{end+1} = sprintf('    L:  %s     # observer gain', mat2yaml_2d(L));
  else
    L_block{end+1} = '    L: null';
  end
  L_block{end+1} = sprintf('    Pf: %s     # terminal cost', mat2yaml_2d(Pf));
  L_block{end+1} = '# === end of auto-generated control: block ===';

  % ── Чтение существующего конфига ──────────────────────────────
  if exist(yaml_path, 'file')
    fid = fopen(yaml_path, 'r', 'n', 'UTF-8');
    text = fread(fid, '*char')';
    fclose(fid);
    lines = strsplit(text, '\n', 'CollapseDelimiters', false);
    % На Windows файл может иметь CRLF-окончания строк; fread возвращает
    % сырые байты, поэтому после strsplit по '\n' каждая строка оканчивается
    % на '\r'. Убираем '\r' в конце каждой строки — иначе «пустые» строки
    % становятся {'\r'} и ломают детектор конца блока (l(1) == char(13)).
    for k = 1:length(lines)
      if ~isempty(lines{k}) && lines{k}(end) == char(13)
        lines{k} = lines{k}(1:end-1);
      end
    end
    % strsplit по тексту, оканчивающемуся на \n, даёт лишний пустой элемент
    % в конце. Если его не убрать, цикл записи (fprintf '%s\n') добавляет по
    % пустой строке в конец файла при каждом экспорте — экспорт перестаёт
    % быть идемпотентным.
    if ~isempty(lines) && isempty(lines{end})
      lines(end) = [];
    end
  else
    lines = {};
  end

  % ── Поиск существующего блока `control:` ──────────────────────
  % Старт: строка, точно начинающаяся с `control:` (без пробелов).
  % Конец: следующая строка с нулевым отступом (новая секция верхнего
  % уровня), либо маркер «end of auto-generated control».
  start_idx = 0; end_idx = 0;
  for i = 1:length(lines)
    l = lines{i};
    if start_idx == 0 && length(l) >= 8 && strcmp(l(1:8), 'control:')
      start_idx = i;
      % Включаем в блок шапку-комментарий от прошлого запуска. Она всегда
      % начинается строкой-маркером «control: section auto-generated». Идём
      % вверх по непрерывным строкам-комментариям и останавливаемся на этом
      % маркере (включительно). Рукописные баннеры выше маркера не трогаем —
      % если маркер не найден (первый экспорт), start_idx остаётся на `control:`.
      hdr = start_idx;
      while hdr > 1 && ~isempty(lines{hdr-1}) && lines{hdr-1}(1) == '#'
        hdr = hdr - 1;
        if ~isempty(strfind(lines{hdr}, 'control: section auto-generated'))
          break;
        end
      end
      if ~isempty(strfind(lines{hdr}, 'control: section auto-generated'))
        start_idx = hdr;
      end
      continue;
    end
    if start_idx > 0 && end_idx == 0
      % Конец блока — строка с нулевым отступом, не комментарий и не пустая
      if ~isempty(l) && l(1) ~= ' ' && l(1) ~= '#' && l(1) ~= 9
        end_idx = i - 1;
        break;
      end
      % Или явный маркер конца
      if ~isempty(strfind(l, 'end of auto-generated control'))
        end_idx = i;
        break;
      end
    end
  end
  if start_idx > 0 && end_idx == 0
    end_idx = length(lines);   % блок до конца файла
  end

  % ── Сборка нового файла ───────────────────────────────────────
  if start_idx > 0
    % Замена существующего блока: до start_idx − новый − после end_idx
    new_lines = [lines(1:start_idx-1), L_block, lines(end_idx+1:end)];
  else
    % Блока не было — добавляем в конец, отделив пустой строкой
    if ~isempty(lines) && ~isempty(lines{end})
      new_lines = [lines, {''}, L_block];
    else
      new_lines = [lines, L_block];
    end
  end

  % ── Запись результата ─────────────────────────────────────────
  fid = fopen(yaml_path, 'w', 'n', 'UTF-8');
  for i = 1:length(new_lines)
    fprintf(fid, '%s\n', new_lines{i});
  end
  fclose(fid);

  fprintf('export_to_yaml: блок control записан в %s (%d строк)\n', ...
          yaml_path, length(L_block));

  % ── Блок mps: (если передан) ──────────────────────────────────
  if nargin >= 9 && ~isempty(mps)
    write_mps_block(yaml_path, mps);
    fprintf('export_to_yaml: блоки control + mps записаны в %s\n', yaml_path);
  end
end

% ── Запись/замена блока mps: ─────────────────────────────────────
function write_mps_block(yaml_path, mps)
% Идемпотентная замена блока mps: между маркерами (тот же приём, что
% для control:). mps.matrices.A/B пишутся НЕПРЕРЫВНЫМИ.
  M = {};
  M{end+1} = '# === mps: section auto-generated by matlab/main.m ===';
  M{end+1} = '# A/B — НЕПРЕРЫВНЫЕ (контракт docs/mps/api.md); бэкенд ZOH-дискретизирует.';
  M{end+1} = 'mps:';
  M{end+1} = '  enabled: true';
  M{end+1} = '';
  M{end+1} = '  plant:';
  M{end+1} = sprintf('    tau_v: %.4f', mps.tau_v);
  M{end+1} = sprintf('    tau_w: %.4f', mps.tau_w);
  M{end+1} = sprintf('    Ts:    %.4f', mps.Ts);
  M{end+1} = '';
  M{end+1} = '  matrices:';
  M{end+1} = sprintf('    A: %s', mat2yaml_2d(mps.A_c));
  M{end+1} = sprintf('    B: %s', mat2yaml_2d(mps.B_c));
  M{end+1} = sprintf('    C: %s', mat2yaml_2d(mps.C));
  M{end+1} = sprintf('    D: %s', mat2yaml_2d(mps.D));
  M{end+1} = '';
  M{end+1} = '  weights:';
  M{end+1} = sprintf('    Q_diag: %s', mat2yaml(diag(mps.Q)'));
  M{end+1} = sprintf('    R_diag: %s', mat2yaml(diag(mps.R)'));
  M{end+1} = '';
  M{end+1} = sprintf('  horizon_N: %d', mps.N);
  M{end+1} = '';
  M{end+1} = '  limits:';
  M{end+1} = sprintf('    u_min: %s', mat2yaml(mps.u_min'));
  M{end+1} = sprintf('    u_max: %s', mat2yaml(mps.u_max'));
  M{end+1} = '';
  M{end+1} = '  scenario:';
  M{end+1} = '    distance_max: 5.0';
  M{end+1} = '    v_target_max: 0.30';
  M{end+1} = '    omega_max_in_forward: 0.5';
  M{end+1} = '    default_distance: 2.0';
  M{end+1} = '    default_v_target: 0.15';
  M{end+1} = '';
  M{end+1} = '  history_size: 20';
  M{end+1} = sprintf('  tick_dt: %.4f', mps.Ts);
  M{end+1} = '# === end of auto-generated mps: block ===';

  fid = fopen(yaml_path, 'r', 'n', 'UTF-8');
  text = fread(fid, '*char')';
  fclose(fid);
  lines = strsplit(text, '\n', 'CollapseDelimiters', false);
  % Убираем '\r' в конце строк (CRLF-файлы на Windows)
  for k = 1:length(lines)
    if ~isempty(lines{k}) && lines{k}(end) == char(13)
      lines{k} = lines{k}(1:end-1);
    end
  end
  if ~isempty(lines) && isempty(lines{end})
    lines(end) = [];
  end

  % Поиск блока mps: — start: строка 'mps:' без отступа (с walk-back на
  % строку-маркер); end: следующий нулевой отступ или end-маркер.
  start_idx = 0; end_idx = 0;
  for i = 1:length(lines)
    l = lines{i};
    if start_idx == 0 && length(l) >= 4 && strcmp(l(1:4), 'mps:')
      start_idx = i;
      hdr = start_idx;
      while hdr > 1 && ~isempty(lines{hdr-1}) && lines{hdr-1}(1) == '#'
        hdr = hdr - 1;
        if ~isempty(strfind(lines{hdr}, 'mps: section auto-generated'))
          break;
        end
      end
      if ~isempty(strfind(lines{hdr}, 'mps: section auto-generated'))
        start_idx = hdr;
      end
      continue;
    end
    if start_idx > 0 && end_idx == 0
      if ~isempty(l) && l(1) ~= ' ' && l(1) ~= '#' && l(1) ~= 9
        end_idx = i - 1;
        break;
      end
      if ~isempty(strfind(l, 'end of auto-generated mps'))
        end_idx = i;
        break;
      end
    end
  end
  if start_idx > 0 && end_idx == 0
    end_idx = length(lines);
  end

  if start_idx > 0
    new_lines = [lines(1:start_idx-1), M, lines(end_idx+1:end)];
  else
    if ~isempty(lines) && ~isempty(lines{end})
      new_lines = [lines, {''}, M];
    else
      new_lines = [lines, M];
    end
  end

  fid = fopen(yaml_path, 'w', 'n', 'UTF-8');
  for i = 1:length(new_lines)
    fprintf(fid, '%s\n', new_lines{i});
  end
  fclose(fid);
end

% ── Локальные хелперы ────────────────────────────────────────────
function s = mat2yaml(v)
% Преобразование 1D-вектора в YAML flow-style список.
% Пример: [1, 2, 3] → '[1, 2, 3]'
  parts = arrayfun(@(x) sprintf('%.6g', x), v, 'UniformOutput', false);
  s = ['[', strjoin(parts, ', '), ']'];
end

function s = mat2yaml_2d(M)
% Преобразование 2D-матрицы в YAML flow-style вложенный список.
% Пример: [1 2; 3 4] → '[[1, 2], [3, 4]]'
  rows = cell(size(M, 1), 1);
  for i = 1:size(M, 1)
    rows{i} = mat2yaml(M(i, :));
  end
  s = ['[', strjoin(rows, ', '), ']'];
end
