function export_to_yaml(Ad, Bd, K_lqr, K_mpc, L, Pf, p, yaml_path)
% EXPORT_TO_YAML — запись рассчитанных матриц в config.yaml (раздел `control:`).
%
%   ЭТО МОСТ MATLAB → ROBOT.
%   После запуска main.m все матрицы регуляторов готовы. Эта функция
%   ПЕРЕЗАПИСЫВАЕТ блок `control:` в config.yaml в корне проекта,
%   сохраняя ВСЕ остальные секции файла нетронутыми. Робот при следующем
%   старте подхватит свежие коэффициенты — перезапуск Python НЕ нужен.
%
%   АЛГОРИТМ:
%     1. Читаем config.yaml как текст (UTF-8).
%     2. Ищем строку, начинающуюся с `control:` без отступа.
%     3. Находим конец блока — следующая строка с зануленным отступом
%        (или маркер `# === end of auto-generated control: block ===`).
%     4. Заменяем диапазон строк новым YAML-блоком.
%     5. Записываем обратно.
%
%   Если `control:` не найден — приписываем блок в конец файла.
%
%   ЗАЩИТА ОТ ПЕРЕЗАПИСИ:
%   В config.yaml есть поле `control.matrices.override`. Если пользователь
%   правил матрицы вручную и не хочет их потерять — должен поставить
%   `override: true`. Эта функция матрицы всё равно перезапишет
%   (лучше всего удалить override после ручной правки), но в комментариях
%   подскажет, как остановить автоматику.
%
%   ВХОДЫ:
%     Ad, Bd       — дискретные матрицы объекта
%     K_lqr        — LQR-регулятор (2 × n)
%     K_mpc        — MPC явный коэффициент первого шага (2 × n)
%     L            — наблюдатель Луенбергера (n × m); [] чтобы пропустить
%     Pf           — терминальный штраф MPC (= P_∞ из DARE)
%     p            — параметры от samurai_params()
%     yaml_path    — полный путь к config.yaml (если [] — берётся ../config.yaml)

  if nargin < 8 || isempty(yaml_path)
    yaml_path = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
                         'config.yaml');
  end

  % ── Сборка нового YAML-блока как cell-массива строк ───────────
  % Пишем человеко-читаемый комментарий, потом параметры, потом матрицы.
  L_block = {};
  L_block{end+1} = '# === control: section auto-generated by matlab/main.m ===';
  L_block{end+1} = '# Edit weights/limits/poles below; rerun matlab/main.m to update matrices.';
  L_block{end+1} = '# Подробное описание: latex_doc/control_theory/main.pdf';
  L_block{end+1} = 'control:';
  L_block{end+1} = '  mode: "off"           # off | lqr | mpc | modal';
  L_block{end+1} = '';
  L_block{end+1} = '  plant:';
  L_block{end+1} = sprintf('    v0:    %.4f', p.v0);
  L_block{end+1} = sprintf('    tau_v: %.4f', p.tau_v);
  L_block{end+1} = sprintf('    tau_w: %.4f', p.tau_w);
  L_block{end+1} = sprintf('    Ts:    %.4f', p.Ts);
  L_block{end+1} = '';
  L_block{end+1} = '  weights:';
  L_block{end+1} = sprintf('    Q_diag: %s', mat2yaml(diag(p.Q)'));
  L_block{end+1} = sprintf('    R_diag: %s', mat2yaml(diag(p.R)'));
  L_block{end+1} = '';
  L_block{end+1} = '  limits:';
  L_block{end+1} = sprintf('    u_min: %s', mat2yaml(p.u_min'));
  L_block{end+1} = sprintf('    u_max: %s', mat2yaml(p.u_max'));
  L_block{end+1} = '';
  L_block{end+1} = '  mpc:';
  L_block{end+1} = sprintf('    horizon_N: %d', p.N);
  L_block{end+1} = '    solver:    "clip"   # clip | qp';
  L_block{end+1} = '';
  L_block{end+1} = '  modal:';
  L_block{end+1} = sprintf('    poles_continuous: %s', mat2yaml(p.poles_continuous'));
  L_block{end+1} = sprintf('    observer_speedup: %.1f', p.observer_speedup);
  L_block{end+1} = '';
  L_block{end+1} = '  matrices:';
  L_block{end+1} = '    override: false      # set true to disable matlab/main.m updates';
  L_block{end+1} = sprintf('    A:  %s', mat2yaml_2d(Ad));
  L_block{end+1} = sprintf('    B:  %s', mat2yaml_2d(Bd));
  L_block{end+1} = sprintf('    K:     %s     # LQR gain (2 x n) — used in mode: lqr', mat2yaml_2d(K_lqr));
  L_block{end+1} = sprintf('    K_mpc: %s     # MPC explicit first-step gain — used in mode: mpc', mat2yaml_2d(K_mpc));
  if ~isempty(L)
    L_block{end+1} = sprintf('    L:  %s     # observer gain', mat2yaml_2d(L));
  else
    L_block{end+1} = '    L: null';
  end
  L_block{end+1} = sprintf('    Pf: %s     # terminal cost', mat2yaml_2d(Pf));
  L_block{end+1} = '# === end of auto-generated control: block ===';

  % ── Чтение существующего конфига ──────────────────────────────
  if exist(yaml_path, 'file')
    fid = fopen(yaml_path, 'r', 'n', 'UTF-8');
    text = fread(fid, '*char')';
    fclose(fid);
    lines = strsplit(text, '\n', 'CollapseDelimiters', false);
  else
    lines = {};
  end

  % ── Поиск существующего блока `control:` ──────────────────────
  % Старт: строка, точно начинающаяся с `control:` (без пробелов).
  % Конец: следующая строка с нулевым отступом (новая секция верхнего
  % уровня), либо маркер «end of auto-generated control».
  start_idx = 0; end_idx = 0;
  for i = 1:length(lines)
    l = lines{i};
    if start_idx == 0 && length(l) >= 8 && strcmp(l(1:8), 'control:')
      start_idx = i;
      % Оборачиваем header-комментарий «=== control: section ===» если он есть
      if i > 1 && ~isempty(strfind(lines{i-1}, 'auto-generated by matlab'))
        start_idx = i - 1;
      end
      if start_idx > 1 && ~isempty(strfind(lines{start_idx-1}, 'control: section'))
        start_idx = start_idx - 1;
      end
      continue;
    end
    if start_idx > 0 && end_idx == 0
      % Конец блока — строка с нулевым отступом, не комментарий и не пустая
      if ~isempty(l) && l(1) ~= ' ' && l(1) ~= '#' && l(1) ~= 9
        end_idx = i - 1;
        break;
      end
      % Или явный маркер конца
      if ~isempty(strfind(l, 'end of auto-generated control'))
        end_idx = i;
        break;
      end
    end
  end
  if start_idx > 0 && end_idx == 0
    end_idx = length(lines);   % блок до конца файла
  end

  % ── Сборка нового файла ───────────────────────────────────────
  if start_idx > 0
    % Замена существующего блока: до start_idx − новый − после end_idx
    new_lines = [lines(1:start_idx-1), L_block, lines(end_idx+1:end)];
  else
    % Блока не было — добавляем в конец, отделив пустой строкой
    if ~isempty(lines) && ~isempty(lines{end})
      new_lines = [lines, {''}, L_block];
    else
      new_lines = [lines, L_block];
    end
  end

  % ── Запись результата ─────────────────────────────────────────
  fid = fopen(yaml_path, 'w', 'n', 'UTF-8');
  for i = 1:length(new_lines)
    fprintf(fid, '%s\n', new_lines{i});
  end
  fclose(fid);

  fprintf('export_to_yaml: блок control записан в %s (%d строк)\n', ...
          yaml_path, length(L_block));
end

% ── Локальные хелперы ────────────────────────────────────────────
function s = mat2yaml(v)
% Преобразование 1D-вектора в YAML flow-style список.
% Пример: [1, 2, 3] → '[1, 2, 3]'
  parts = arrayfun(@(x) sprintf('%.6g', x), v, 'UniformOutput', false);
  s = ['[', strjoin(parts, ', '), ']'];
end

function s = mat2yaml_2d(M)
% Преобразование 2D-матрицы в YAML flow-style вложенный список.
% Пример: [1 2; 3 4] → '[[1, 2], [3, 4]]'
  rows = cell(size(M, 1), 1);
  for i = 1:size(M, 1)
    rows{i} = mat2yaml(M(i, :));
  end
  s = ['[', strjoin(rows, ', '), ']'];
end
