function test_export_to_yaml()
% Regression test for export_to_yaml.m — the `control:` block rewrite must be
% IDEMPOTENT.
%
% Bug: the start-of-block walk-back did not recognise the 3-line auto-generated
% header on a re-run, so each re-export orphaned the previous header comments
% and prepended fresh ones. In the real config.yaml they had stacked up 3x,
% and the stale hand-written block left below the end-marker was never
% replaced — which is what shadowed the control matrices with nulls.
%
% Run:  matlab -batch "addpath('matlab'); test_export_to_yaml"

  here = fileparts(mfilename('fullpath'));
  addpath(here);

  % -- minimal plant params + dummy matrices ------------------------------
  p = struct();
  p.v0 = 0.2; p.tau_v = 0.15; p.tau_w = 0.10; p.Ts = 0.05;
  p.Q = diag([10 10 5 1 1]); p.R = diag([1 1]);
  p.u_min = [-0.3; -2]; p.u_max = [0.3; 2];
  p.N = 10;
  p.poles_continuous = [-2 -3 -4 -8 -10];
  p.observer_speedup = 5.0;
  Ad = eye(5); Bd = ones(5, 2);
  K_lqr = ones(2, 5); K_mpc = ones(2, 5); L = ones(5, 5); Pf = eye(5);

  % -- fixture: a config with a hand-written control: block ---------------
  tmp = [tempname '.yaml'];
  fid = fopen(tmp, 'w', 'n', 'UTF-8');
  fprintf(fid, 'network:\n  port: 5000\n\n');
  fprintf(fid, 'control:\n  mode: "off"\n  legacy: true\n\n');
  fprintf(fid, 'simulator:\n  fps: 30\n');
  fclose(fid);
  cleanup = onCleanup(@() delete(tmp));

  % -- export three times; every rewrite must produce identical output ----
  export_to_yaml(Ad, Bd, K_lqr, K_mpc, L, Pf, p, tmp);
  after1 = fileread(tmp, 'Encoding', 'UTF-8');
  export_to_yaml(Ad, Bd, K_lqr, K_mpc, L, Pf, p, tmp);
  after2 = fileread(tmp, 'Encoding', 'UTF-8');
  export_to_yaml(Ad, Bd, K_lqr, K_mpc, L, Pf, p, tmp);
  after3 = fileread(tmp, 'Encoding', 'UTF-8');

  assert(strcmp(after1, after2), ...
    'export_to_yaml is not idempotent: rewrite #2 differs from rewrite #1');
  assert(strcmp(after2, after3), ...
    'export_to_yaml is not idempotent: rewrite #3 differs from rewrite #2');

  % -- exactly one of each structural marker ------------------------------
  n_header  = numel(strfind(after3, ...
    '# === control: section auto-generated by matlab/main.m ==='));
  n_endmark = numel(strfind(after3, ...
    '# === end of auto-generated control: block ==='));
  n_control = numel(regexp(after3, '(^|\n)control:', 'start'));
  assert(n_header == 1,  sprintf('expected 1 auto-gen header, got %d', n_header));
  assert(n_endmark == 1, sprintf('expected 1 end marker, got %d', n_endmark));
  assert(n_control == 1, sprintf('expected 1 control: key, got %d', n_control));

  % -- surrounding sections untouched -------------------------------------
  assert(~isempty(strfind(after3, 'network:')),   'network: section lost');
  assert(~isempty(strfind(after3, 'simulator:')), 'simulator: section lost');

  fprintf('PASS: export_to_yaml idempotent — 1 header / 1 control: / 1 end marker\n');
end
