#!/usr/bin/env bash
# Generate requirements.lock from the current Python environment.
#
# Run this ON the target deployment platform (Pi 4 arm64 for the robot,
# x86_64 Linux for the compute laptop) AFTER `pip install -r requirements.txt`
# has succeeded. The output captures the resolved transitive dep tree —
# safe to install with `pip install --no-deps -r requirements.lock` for
# reproducible deploys.
#
# requirements.lock is .gitignored because each platform produces a different
# resolution (numpy ABI tags, arm64 wheels, etc.) and committing one would
# break the others.

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v pip >/dev/null 2>&1; then
    echo "pip not found — install Python first" >&2
    exit 1
fi

OUT="requirements.lock"
TMP="$(mktemp)"

{
    echo "# Generated by scripts/lock-requirements.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Platform: $(python3 -c 'import platform; print(platform.platform())')"
    echo "# Python:   $(python3 -V 2>&1)"
    echo "# Install with: pip install --no-deps -r requirements.lock"
    echo
    pip freeze --exclude-editable
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
